# Site wide configuration

title:            My Tech Blog
locale:           en_US
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Unais T
  avatar: unais.jpg
  bio: "I am tech geek ,very much intrested to learn and experiment with new technologies. Especially Robotics,Machine Vision, Machine Learning, AI etc."
  email: tpunais@gmail.com
  disqus-shortname: 
  twitter: unais_t
  facebook: unais.thachuparampil
  google:
    plus: UnaisT
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: unais
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
